"""Extract automated actions and server actions.

Inspects:

* ``base.automation`` (Studio / Automation rules)
* ``ir.actions.server`` (server actions, possibly generated by Studio)
* ``ir.cron`` (scheduled actions, where useful)
"""

from __future__ import annotations

from typing import Any, Iterable

from ..client import OdooClient, OdooClientError


SERVER_ACTION_FIELDS: tuple[str, ...] = (
    "id",
    "name",
    "model_id",
    "model_name",
    "state",
    "type",
    "code",
    "usage",
    "sequence",
    "binding_model_id",
    "binding_type",
    "binding_view_types",
)


AUTOMATION_FIELDS: tuple[str, ...] = (
    "id",
    "name",
    "model_id",
    "model_name",
    "state",
    "active",
    "trigger",
    "trigger_field_ids",
    "filter_pre_domain",
    "filter_domain",
    "on_change_field_ids",
    "action_server_id",
)


CRON_FIELDS: tuple[str, ...] = (
    "id",
    "name",
    "model_id",
    "state",
    "active",
    "interval_number",
    "interval_type",
    "numbercall",
    "code",
    "user_id",
)


def _domain_for_models(models: Iterable[str] | None) -> list[Any]:
    """Build a domain that filters by ``model_name in models`` if provided."""
    models = list(models or [])
    if not models:
        return []
    return [("model_name", "in", models)]


def extract_server_actions(
    client: OdooClient,
    warnings: list[str] | None = None,
    *,
    custom_models: Iterable[str] | None = None,
) -> list[dict[str, Any]]:
    """Return server actions, optionally filtered by custom model names."""
    warnings = warnings if warnings is not None else []
    domain = _domain_for_models(custom_models)
    try:
        return client.search_read(
            "ir.actions.server",
            domain,
            list(SERVER_ACTION_FIELDS),
            order="model_name asc, name asc",
        )
    except OdooClientError as exc:
        warnings.append(f"ir.actions.server extraction failed: {exc}")
        return []


def extract_automations(
    client: OdooClient,
    warnings: list[str] | None = None,
    *,
    custom_models: Iterable[str] | None = None,
) -> list[dict[str, Any]]:
    """Return ``base.automation`` records (returns [] if model not installed)."""
    warnings = warnings if warnings is not None else []

    if not client.model_exists("base.automation"):
        warnings.append(
            "base.automation model is not available on this Odoo "
            "instance (module 'base_automation' may not be installed)."
        )
        return []

    domain = _domain_for_models(custom_models)
    try:
        return client.search_read(
            "base.automation",
            domain,
            list(AUTOMATION_FIELDS),
            order="model_name asc, name asc",
        )
    except OdooClientError as exc:
        warnings.append(f"base.automation extraction failed: {exc}")
        return []


def extract_crons(
    client: OdooClient,
    warnings: list[str] | None = None,
) -> list[dict[str, Any]]:
    """Return scheduled actions (``ir.cron``) — useful for completeness."""
    warnings = warnings if warnings is not None else []
    try:
        return client.search_read(
            "ir.cron",
            [],
            list(CRON_FIELDS),
            order="name asc",
        )
    except OdooClientError as exc:
        warnings.append(f"ir.cron extraction failed: {exc}")
        return []
