"""Extract automated actions and server actions.

Inspects:

* ``base.automation`` (Studio / Automation rules)
* ``ir.actions.server`` (server actions, possibly generated by Studio)
* ``ir.cron`` (scheduled actions, where useful)
"""

from __future__ import annotations

from typing import Any, Iterable

from ..client import OdooClient, OdooClientError


def safe_fields(
    client: OdooClient,
    model_name: str,
    requested_fields: Iterable[str],
    warnings: list[str] | None = None,
) -> list[str]:
    """Filter requested fields to only those that exist in the model.

    Calls ``fields_get`` on the model and returns the intersection of
    ``requested_fields`` with the actual fields available. If any requested
    fields are missing, a warning is appended to ``warnings``.

    Args:
        client: Authenticated OdooClient instance.
        model_name: The Odoo model name (e.g., "base.automation").
        requested_fields: Fields we'd like to read.
        warnings: Optional list to append warnings to.

    Returns:
        A list of field names that are safe to use in search_read.
    """
    warnings = warnings if warnings is not None else []
    try:
        available = client.fields_get(model_name)
        available_set = set(available.keys())
        requested_set = set(requested_fields)
        safe = requested_set & available_set
        missing = requested_set - available_set
        if missing:
            warnings.append(
                f"{model_name}: skipped unavailable fields: {', '.join(sorted(missing))}"
            )
        return sorted(safe)
    except OdooClientError as exc:
        warnings.append(
            f"{model_name}: could not retrieve field metadata: {exc}. "
            f"Using all requested fields."
        )
        return list(requested_fields)


SERVER_ACTION_FIELDS: tuple[str, ...] = (
    "id",
    "name",
    "model_id",
    "model_name",
    "state",
    "type",
    "code",
    "usage",
    "sequence",
    "binding_model_id",
    "binding_type",
    "binding_view_types",
)


AUTOMATION_FIELDS: tuple[str, ...] = (
    "id",
    "name",
    "model_id",
    "model_name",
    "state",
    "active",
    "trigger",
    "trigger_field_ids",
    "filter_pre_domain",
    "filter_domain",
    "on_change_field_ids",
    "action_server_id",
)


CRON_FIELDS: tuple[str, ...] = (
    "id",
    "name",
    "model_id",
    "state",
    "active",
    "interval_number",
    "interval_type",
    "numbercall",
    "code",
    "user_id",
)


def _domain_for_models(models: Iterable[str] | None) -> list[Any]:
    """Build a domain that filters by ``model_name in models`` if provided."""
    models = list(models or [])
    if not models:
        return []
    return [("model_name", "in", models)]


def extract_server_actions(
    client: OdooClient,
    warnings: list[str] | None = None,
    *,
    custom_models: Iterable[str] | None = None,
) -> list[dict[str, Any]]:
    """Return server actions, optionally filtered by custom model names."""
    warnings = warnings if warnings is not None else []
    domain = _domain_for_models(custom_models)
    fields = safe_fields(client, "ir.actions.server", SERVER_ACTION_FIELDS, warnings)
    if not fields:
        warnings.append(
            "ir.actions.server: no valid fields available, skipping extraction."
        )
        return []
    try:
        return client.search_read(
            "ir.actions.server",
            domain,
            fields,
            order="model_name asc, name asc",
        )
    except OdooClientError as exc:
        warnings.append(f"ir.actions.server extraction failed: {exc}")
        return []


def extract_automations(
    client: OdooClient,
    warnings: list[str] | None = None,
    *,
    custom_models: Iterable[str] | None = None,
) -> list[dict[str, Any]]:
    """Return ``base.automation`` records (returns [] if model not installed)."""
    warnings = warnings if warnings is not None else []

    if not client.model_exists("base.automation"):
        warnings.append(
            "base.automation model is not available on this Odoo "
            "instance (module 'base_automation' may not be installed)."
        )
        return []

    domain = _domain_for_models(custom_models)
    fields = safe_fields(client, "base.automation", AUTOMATION_FIELDS, warnings)
    if not fields:
        warnings.append(
            "base.automation: no valid fields available, skipping extraction."
        )
        return []
    try:
        return client.search_read(
            "base.automation",
            domain,
            fields,
            order="model_name asc, name asc",
        )
    except OdooClientError as exc:
        warnings.append(f"base.automation extraction failed: {exc}")
        return []


def extract_crons(
    client: OdooClient,
    warnings: list[str] | None = None,
) -> list[dict[str, Any]]:
    """Return scheduled actions (``ir.cron``) — useful for completeness."""
    warnings = warnings if warnings is not None else []
    fields = safe_fields(client, "ir.cron", CRON_FIELDS, warnings)
    if not fields:
        warnings.append(
            "ir.cron: no valid fields available, skipping extraction."
        )
        return []
    try:
        return client.search_read(
            "ir.cron",
            [],
            fields,
            order="name asc",
        )
    except OdooClientError as exc:
        warnings.append(f"ir.cron extraction failed: {exc}")
        return []
